name: Update API Data

on:
  schedule:
    # # Run every Tuesday at 03:00 Beijing Time (19:00 UTC)
    - cron: '0 19 * * 2'
  workflow_dispatch: # Allow manual trigger

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Install utils
        run: |
          sudo apt-get update
          sudo apt-get install -y zstd

      - uses: actions/checkout@v4
        with:
          ref: packages-index
          fetch-depth: 0
          persist-credentials: false

      - name: Old HEAD
        run: |
          OLD_SHA="$(git rev-parse HEAD)"
          echo "OLD_SHA=$OLD_SHA" >> "$GITHUB_ENV"

      - name: Fetch upstream HEAD
        run: |
          git fetch --no-tags \
            "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/ruyisdk/packages-index.git" \
            main
          UPSTREAM_SHA="$(git rev-parse FETCH_HEAD)"
          echo "UPSTREAM_SHA=$UPSTREAM_SHA" >> "$GITHUB_ENV"

      - name: Check changes
        if: env.OLD_SHA != env.UPSTREAM_SHA
        env:
          GH_TOKEN: ${{ secrets.PUSH_PAT }}
        run: |
          WATCH_PATH="packages entities config.toml"

          git reset --hard "$UPSTREAM_SHA"

          if ! git diff --quiet "${OLD_SHA}" "${UPSTREAM_SHA}" -- ${WATCH_PATH}; then

            TAR=images.tar.zstd
            TAG=$(date -u +%Y%m%d)
            RUN="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            
            tar --zstd -cf ${TAR} ${WATCH_PATH}

            gh release create "${TAG}" \
              --title "${TAG}" \
              --notes "Auto release https://github.com/ruyisdk/packages-index/tree/${UPSTREAM_SHA}\nAction run: ${RUN}" \
              --target packages-index

            gh release upload "${TAG}" "${TAR}"

          fi
          git push "https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git" HEAD:packages-index

